app/uk/gov/hmrc/vatsignupfrontend/forms/YesNoForm.scala, app/uk/gov/hmrc/vatsignupfrontend/models/YesNo.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/multiple_vat_check.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/MultipleVatCheckViewSpec.scala
=> SAR-2241: Create new view to check if the user has more than one

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/BusinessPostCodeController.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/business_postcode.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/BusinessPostCodeSpec.scala
Reverts hmrc/vat-sign-up-frontend#62
=> Revert "SAR-2259: updated content for business post code page"

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/BusinessPostCodeController.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/principal_place_of_business.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/PrincipalPlaceOfBusinessSpec.scala
Reverts hmrc/vat-sign-up-frontend#69
=> Revert "Revert "SAR-2259: updated content for business post code page""

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/ResolveVatNumberController.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/ResolveVatNumberControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/ResolveVatNumberControllerSpec.scala
Update the controller to redirect to the newly created
controller for checking if the user has more than one
vat registration.
=> SAR-2245: Update resolve vat controller redirect

app/uk/gov/hmrc/vatsignupfrontend/views/agent/confirm_company.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/agent/ConfirmCompanySpec.scala
This is a copy of the view created for the agent journey.
=> SAR-2273: Create new view to confirm company name

app/uk/gov/hmrc/vatsignupfrontend/config/AppConfig.scala, app/uk/gov/hmrc/vatsignupfrontend/views/agent/agree_capture_email.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent/already_signed_up.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent/cannot_use_service_yet.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent/company_name_not_found.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent/could_not_confirm_vat_number.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent/failed_client_matching.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent/no_agent_client_relationship.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent/not_enrolled_to_agent_services.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent_main_template.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/govuk_wrapper.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/helpers/signOutButton.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/helpers/signOutLink.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/main_template.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/agree_capture_email.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/already_signed_up.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/assistant_credential_error.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/cannot_use_service_yet.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/company_name_not_found.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/could_not_confirm_business.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/could_not_confirm_vat_number.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/failed_identity_verification.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/failed_matching.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/incorrect_enrolment_vat_number.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/information_received.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/sign_in_with_different_details.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/sole_trader_different_details.scala.html, conf/application.conf
Reverts hmrc/vat-sign-up-frontend#94
=> Revert "Changed the redirection for the agent and principal exit surveys"

app/uk/gov/hmrc/vatsignupfrontend/config/AppConfig.scala, app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CheckYourAnswersController.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CheckYourAnswersControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CheckYourAnswersControllerSpec.scala
Reverts hmrc/vat-sign-up-frontend#124
=> Revert "SAR-2511: for users who came from bta and their known facts were a mi…"

app/uk/gov/hmrc/vatsignupfrontend/controllers/agent/CaptureCompanyNumberController.scala, app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureCompanyNumberController.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/agent/CaptureCompanyNumberControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureCompanyNumberControllerSpec.scala
Update CaptureCompanyNumberController to only support
the company name journey.
=> SAR-2796: Update capture company number

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityController.scala, app/uk/gov/hmrc/vatsignupfrontend/forms/BusinessEntityForm.scala, app/uk/gov/hmrc/vatsignupfrontend/models/BusinessEntity.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/capture_business_entity.scala.html, conf/messages, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CaptureBusinessEntitySpec.scala
Update capture business entity page to support unincorporated
association, and add a couple of fixes for division.
=> SAR-3015: Update capture business entity page

app/uk/gov/hmrc/vatsignupfrontend/forms/HaveSoftwareForm.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/have_software.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/HaveSoftwareViewSpec.scala
__DEPLOY__ : This view contains a made up error message,
it needs to change when design provides it.
=> SAR-3060: New have software view

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/AgentUsingPrincipalJourneyController.scala, conf/principal.routes, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/AgentUsingPrincipalJourneyControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/AgentUsingPrincipalJourneyControllerSpec.scala
SAR-3190 - Tweaked integration test labels
=> SAR-3190 - Add AgentUsingPrincipalJourneyController

app/uk/gov/hmrc/vatsignupfrontend/config/AppConfig.scala, app/uk/gov/hmrc/vatsignupfrontend/connectors/StoreOverseasInformationConnector.scala, app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/OverseasResolverController.scala, app/uk/gov/hmrc/vatsignupfrontend/httpparsers/StoreOverseasInformationHttpParser.scala, app/uk/gov/hmrc/vatsignupfrontend/services/StoreOverseasInformationService.scala, conf/principal.routes, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/OverseasResolverControllerISpec.scala, it/uk/gov/hmrc/vatsignupfrontend/helpers/servicemocks/StoreOverseasInformationStub.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/OverseasResolverControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/httpparsers/StoreOverseasInformationHttpParserSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/services/mocks/MockStoreOverseasInformationService.scala
Add necessary files to support storing the overseas vat number.
=> SAR-3287: Add resolver, service, parser and connector

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CheckYourAnswersController.scala, app/uk/gov/hmrc/vatsignupfrontend/views/helpers/CheckYourAnswersIdConstants.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/check_your_answers.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBox5FigureControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/helpers/TestConstants.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CheckYourAnswersViewSpec.scala
SAR-3341: Additional KFs on CheckYourAnswers
Tweak to test constants
=> SAR-3341: Additional KFs on CheckYourAnswers

app/uk/gov/hmrc/vatsignupfrontend/utils/StringUtils.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/check_your_answers.scala.html, test/uk/gov/hmrc/vatsignupfrontend/utils/CurrencyFormatSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CheckYourAnswersViewSpec.scala
SAR-3377: Currency formatting utility
SAR-3377: Tests
=> SAR-3377: Currency formatting utility

app/uk/gov/hmrc/vatsignupfrontend/config/featureswitch/FeatureSwitch.scala, build.sbt, run.sh
- included change to set default port as part of build.sbt to 9956
- added run shell script to simplify starting of service with testOnly routes as the router
=> [SAR-3390] Added Feature Switch for DD T&Cs Journey

public/stylesheets/local-overrides.css
Local override fix due to time constraints. Ideally this should be re-implemented using HTML tables when we have more time
=> SAR-3429: Fix layout of CYA tables

conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala
**DO NOT MERGE UNTIL 8TH MARCH**
=> SAR-3371 - Reset content to pre stagger 2 block

app/uk/gov/hmrc/vatsignupfrontend/views/principal/direct_debit_terms_and_conditions.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/DirectDebitTermsAndConditionsSpec.scala
**Notes**:
- Waiting on the URL for the DD T&Cs hand-off; currently this is set to `#` with a `TODO` comment
- PP with @LadonJackson
=> [SAR-3412] Added view for Direct Debit T&Cs Agreement

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/DirectDebitResolverController.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/DirectDebitResolverControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/DirectDebitResolverControllerSpec.scala
**Notes:**
- Links DD Resolver to controllers
- PRs for `SAR-3413` #443 and `SAR-3409` #439 need to be reviewed and merged first.
=> [SAR-3416] Update DD Resolver Controller routing

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/TermsController.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/send_your_application.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/TermsControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/ViewSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/SendYourApplicationSpec.scala
**Note:** PR for `SAR-3460` #473 should be reviewed and merged prior to this.
=> [SAR-3461] Updated the TermsController to render view based on SendYourApplication feature switch

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/TermsController.scala, app/uk/gov/hmrc/vatsignupfrontend/views/agent/send_your_application.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/send_your_application.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/TermsControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/ViewSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/agent/SendYourApplicationSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/SendYourApplicationSpec.scala
**Notes:**
- PR for `SAR-3460` #473 should be reviewed and merged prior to this PR
- PR for `SAR-3461` #474 should be reviewed and merged prior to this PR
=> [SAR-3464] Add SendYourApplication Agent view

app/uk/gov/hmrc/vatsignupfrontend/config/featureswitch/FeatureSwitch.scala, app/uk/gov/hmrc/vatsignupfrontend/controllers/agent/TermsController.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/agent/TermsControllerSpec.scala
=> [SAR-3465] updated TermsController to show send your application when enabled

app/uk/gov/hmrc/vatsignupfrontend/controllers/agent/partnerships/JointVenturePropertyController.scala, conf/agent.routes, it/uk/gov/hmrc/vatsignupfrontend/controllers/agent/partnerships/JointVenturePropertyControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/agent/partnerships/JointVenturePropertyControllerSpec.scala
Shouldn't be merged until after #489
=> [SAR-3472] added JointVenturePropertyController and routes

conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala
It's actually SAR-3564 (typo!)
=> SAR-3546: Fix incorrect messages

conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala
Reverts hmrc/vat-sign-up-frontend#524
=> Revert "SAR-3579: Changed content of cannot use service page"

app/uk/gov/hmrc/vatsignupfrontend/views/principal/capture_box_5_figure.scala.html, conf/messages, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CaptureBox5FigureSpec.scala
SAR-3514: Correct accidental typo in messages file
=> SAR-3514: Update content on capture box 5 figure page

app/uk/gov/hmrc/vatsignupfrontend/SessionKeys.scala, app/uk/gov/hmrc/vatsignupfrontend/config/featureswitch/FeatureSwitch.scala, app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/soletrader/CaptureNinoController.scala, conf/principal.routes, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/soletrader/CaptureNinoControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/soletrader/CaptureNinoControllerSpec.scala
SAR-3677: Check session key in POST unit test
=> SAR-3677: Capture NINO controller (principal)

app/uk/gov/hmrc/vatsignupfrontend/controllers/agent/CaptureBusinessEntityController.scala, app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityController.scala, app/uk/gov/hmrc/vatsignupfrontend/forms/BusinessEntityForm.scala, app/uk/gov/hmrc/vatsignupfrontend/views/agent/capture_business_entity.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/helpers/radioHelper.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/capture_business_entity.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/principal/capture_business_entity_other.scala.html, conf/messages, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityControllerISpec.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityOtherControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityOtherControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CtEnrolmentDetailsDoNotMatchControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/forms/BusinessEntityFormSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/agent/CaptureBusinessEntitySpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CaptureBusinessEntitySpec.scala
Updated select business entity page to have less options,
Included or text between limited company and other radio options,
Redirect the user to the other business entity page when they select other,
Updated tests.
=> SAR-3815 - Updated the business entity page for the new flow

app/uk/gov/hmrc/vatsignupfrontend/views/principal/making_tax_digital_software.scala.html, conf/messages, conf/messages.cy, public/stylesheets/local-overrides.css, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/MakingTaxDigitalSoftwareViewSpec.scala
Below image shows how the page renders.
=> SAR-4236 - Created the 1st interrupt card view

app/uk/gov/hmrc/vatsignupfrontend/config/AppConfig.scala, app/uk/gov/hmrc/vatsignupfrontend/views/principal/got_software.scala.html, conf/application.conf, conf/messages, conf/messages.cy, public/stylesheets/local-overrides.css, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/GotSoftwareViewSpec.scala
Below image is how the page renders
=> SAR-4238 - Created new view for the 3rd interrupt card

app/uk/gov/hmrc/vatsignupfrontend/views/principal/eligibility/use_spreadsheets.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/eligibility/UseSpreadsheetsViewSpec.scala
Below image is how the page is rendered
=> SAR-4239 - Created new view for the 4th interrupt page

app/uk/gov/hmrc/vatsignupfrontend/views/principal/eligibility/not_got_software.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/eligibility/NotGotSoftwareSpec.scala
=> SAR-4240: Not Got Software view

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureVatNumberController.scala, app/uk/gov/hmrc/vatsignupfrontend/services/GetCompanyNameService.scala, app/uk/gov/hmrc/vatsignupfrontend/utils/StringPaddingUtil.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/agent/CaptureCompanyNumberControllerISpec.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/agent/CaptureRegisteredSocietyCompanyNumberControllerISpec.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/agent/partnerships/AgentCapturePartnershipCompanyNumberControllerISpec.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureCompanyNumberControllerISpec.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureRegisteredSocietyCompanyNumberControllerISpec.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/partnerships/CapturePartnershipCompanyNumberControllerISpec.scala, it/uk/gov/hmrc/vatsignupfrontend/helpers/IntegrationTestConstants.scala, test/uk/gov/hmrc/vatsignupfrontend/services/GetCompanyNameServiceSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/utils/StringPaddingUtilSpec.scala
Also tidied up some logic in CaptureVatNumberController
=> SAR-4675: Pad short CRNs

app/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityController.scala, it/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/principal/CaptureBusinessEntityControllerSpec.scala
Update individual business entity controller to route to overseas resolver controller
=> SAR-5042 - Update overseas routing

app/uk/gov/hmrc/vatsignupfrontend/views/agent/capture_business_entity.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/agent/capture_business_entity_other.scala.html
SAR-5555:Removed duplicated legends from business entity 
* [] I've run a dependency check to ensure all dependencies are up to date
=> SAR-5555: removed duplicated legend

app/uk/gov/hmrc/vatsignupfrontend/controllers/agent/ConfirmationController.scala, app/uk/gov/hmrc/vatsignupfrontend/views/agent/confirmation.scala.html, conf/messages, conf/messages.cy, it/uk/gov/hmrc/vatsignupfrontend/controllers/agent/ConfirmationControllerISpec.scala, test/uk/gov/hmrc/vatsignupfrontend/assets/MessageLookup.scala, test/uk/gov/hmrc/vatsignupfrontend/controllers/agent/ConfirmationControllerSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/agent/ConfirmationViewSpec.scala
Page Content changes updated and all relevant tests.
New tests added for added content
=> SAR-5735 Content change to Information Received Agent Journey

app/uk/gov/hmrc/vatsignupfrontend/views/agent/confirmation.scala.html, app/uk/gov/hmrc/vatsignupfrontend/views/govuk_wrapper.scala.html, public/stylesheets/local-overrides.css
Defaulted language toggle to right, added exception for smaller screen to go back to the left under a certain screen width.
=> SAR-5781 Changed styling for language toggle to right align default

test/uk/gov/hmrc/vatsignupfrontend/views/agent/partnerships/CheckYourAnswersViewSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CheckYourAnswersCompanyViewSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CheckYourAnswersFinalViewSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CheckYourAnswersRegisteredSocietySpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/CheckYourAnswersViewSpec.scala, test/uk/gov/hmrc/vatsignupfrontend/views/principal/partnerships/CheckYourAnswersPartnershipsViewSpec.scala
Make all CYA specs extend SummarySectionTesting
Remove duplicate methods from specs
=> SAR-5791 Making all CYA specs extend SummarySectionTesting
